-- ============================================================
-- TABLA: horario
-- ============================================================
CREATE TABLE IF NOT EXISTS public.horario (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code    VARCHAR(10) NOT NULL,
  shudle  VARCHAR(20) NOT NULL,
  status  INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE public.horario ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- SEED DATA
-- ============================================================
INSERT INTO public.horario (code, shudle, status) VALUES
  ('830', '08:30 AM', 0),
  ('630', '06:30 AM', 0)
ON CONFLICT DO NOTHING;

-- ============================================================
-- RLS POLICIES
-- ============================================================
DROP POLICY IF EXISTS "horario_select_all" ON public.horario;
CREATE POLICY "horario_select_all" ON public.horario
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "horario_insert_admin" ON public.horario;
CREATE POLICY "horario_insert_admin" ON public.horario
  FOR INSERT TO authenticated WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "horario_update_admin" ON public.horario;
CREATE POLICY "horario_update_admin" ON public.horario
  FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "horario_delete_admin" ON public.horario;
CREATE POLICY "horario_delete_admin" ON public.horario
  FOR DELETE TO authenticated USING (public.is_admin());

-- ============================================================
-- RPC: manage_horario
-- ============================================================
CREATE OR REPLACE FUNCTION public.manage_horario(
  p_action    VARCHAR,
  p_id        BIGINT DEFAULT NULL,
  p_code      VARCHAR DEFAULT NULL,
  p_shudle    VARCHAR DEFAULT NULL,
  p_status    INTEGER DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_horario JSON;
BEGIN
  IF NOT public.is_admin() THEN
    RETURN json_build_object('success', false, 'message', 'Solo administradores pueden realizar esta accion.');
  END IF;

  IF LOWER(p_action) = 'create' THEN
    WITH inserted AS (
      INSERT INTO public.horario (code, shudle, status)
      VALUES (p_code, p_shudle, COALESCE(p_status, 0))
      RETURNING *
    )
    SELECT row_to_json(inserted.*) INTO v_horario FROM inserted;
    RETURN json_build_object('success', true, 'data', v_horario, 'message', 'Horario creado con exito.');

  ELSIF LOWER(p_action) = 'update' THEN
    WITH updated AS (
      UPDATE public.horario SET
        code   = COALESCE(p_code, code),
        shudle = COALESCE(p_shudle, shudle),
        status = COALESCE(p_status, status)
      WHERE id = p_id
      RETURNING *
    )
    SELECT row_to_json(updated.*) INTO v_horario FROM updated;
    RETURN json_build_object('success', true, 'data', v_horario, 'message', 'Horario actualizado con exito.');

  ELSIF LOWER(p_action) = 'delete' THEN
    DELETE FROM public.horario WHERE id = p_id;
    RETURN json_build_object('success', true, 'message', 'Horario eliminado del sistema.');

  ELSE
    RETURN json_build_object('success', false, 'message', 'Accion no reconocida.');
  END IF;

EXCEPTION WHEN OTHERS THEN
  RETURN json_build_object('success', false, 'message', 'Error: ' || SQLERRM);
END;
$$;

NOTIFY pgrst, 'reload schema';
