-- BACKUP: ESTRUCTURA DE TABLAS

-- >>> ELIMINACIÓN DE TABLAS <<<
DROP TABLE IF EXISTS public."clients" CASCADE;
DROP TABLE IF EXISTS public."units" CASCADE;
DROP TABLE IF EXISTS public."route_horarios" CASCADE;
DROP TABLE IF EXISTS public."recharge" CASCADE;
DROP TABLE IF EXISTS public."company" CASCADE;
DROP TABLE IF EXISTS public."profiles" CASCADE;
DROP TABLE IF EXISTS public."user_routes" CASCADE;
DROP TABLE IF EXISTS public."horario" CASCADE;
DROP TABLE IF EXISTS public."transactions" CASCADE;
DROP TABLE IF EXISTS public."solicitude" CASCADE;
DROP TABLE IF EXISTS public."debug_manage_profile" CASCADE;
DROP TABLE IF EXISTS public."routes" CASCADE;
DROP TABLE IF EXISTS public."v_role" CASCADE;
DROP TABLE IF EXISTS public."bank_info" CASCADE;
DROP TABLE IF EXISTS public."careers" CASCADE;

-- >>> TIPOS ENUM <<<
DROP TYPE IF EXISTS public."user_role" CASCADE;
CREATE TYPE public.user_role AS ENUM ('admin', 'student', 'driver', 'supervisor');

-- >>> SECUENCIAS <<<
CREATE SEQUENCE IF NOT EXISTS public."careers_id_seq";

CREATE TABLE IF NOT EXISTS public."clients" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying(255) NOT NULL, "phone" character varying(255) NOT NULL, "documentID" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "creditLimit" character varying(255) NOT NULL, "status" character varying(255) NOT NULL, "createAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, "createBy" character varying(255) NOT NULL, "carrer" character varying(255), "balance" numeric NOT NULL, "uid" character varying(1000) NOT NULL, "idroute" bigint, "photo_url" character varying(1000));

CREATE TABLE IF NOT EXISTS public."units" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying(255) NOT NULL, "number" character varying(255) NOT NULL, "plate" character varying(255) NOT NULL, "status" integer NOT NULL, "driver" character varying(255) NOT NULL, "idroute" bigint, "email" character varying(255), "photo_url" character varying(1000));

CREATE TABLE IF NOT EXISTS public."route_horarios" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "idroute" bigint NOT NULL, "idhorario" bigint NOT NULL);

CREATE TABLE IF NOT EXISTS public."recharge" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "idclient" integer NOT NULL, "method" character varying(255) NOT NULL, "ref" character varying(255), "picture" character varying(1000), "amount" numeric NOT NULL, "tasa" numeric, "date" date NOT NULL, "status" integer NOT NULL, "createBy" character varying(255), "createAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP, "updateAprobate" timestamp without time zone, "codigo_banco" character varying(4), "idroute" bigint, "tickets" numeric, "idshedule" bigint);

CREATE TABLE IF NOT EXISTS public."company" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying(255), "rif" character varying(255), "phone" character varying(255), "ticket" numeric NOT NULL, "tasa" numeric NOT NULL, "account" character varying(2000), "phoneAccount" character varying(255), "rifAccount" character varying(255));

CREATE TABLE IF NOT EXISTS public."profiles" ("id" uuid NOT NULL, "email" text NOT NULL, "role" "user_role" NOT NULL DEFAULT 'student'::user_role, "updated_at" timestamp with time zone DEFAULT now(), "name" text);

CREATE TABLE IF NOT EXISTS public."user_routes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" uuid NOT NULL, "idroute" bigint NOT NULL, "created_at" timestamp with time zone DEFAULT now());

CREATE TABLE IF NOT EXISTS public."horario" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "code" character varying(10) NOT NULL, "shudle" character varying(20) NOT NULL, "status" integer NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS public."transactions" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "uid" character varying(255) NOT NULL, "idclient" integer NOT NULL, "createBy" integer NOT NULL, "amount" numeric NOT NULL, "status" integer NOT NULL, "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, "idunit" integer NOT NULL, "shedule" character varying(255), "newBalanceClient" numeric, "idroute" bigint);

CREATE TABLE IF NOT EXISTS public."solicitude" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "date" character varying(11) NOT NULL, "idclient" integer NOT NULL, "shedule" character varying(255) NOT NULL, "route" character varying(255), "status" smallint, "idroute" bigint);

CREATE TABLE IF NOT EXISTS public."debug_manage_profile" ("ts" timestamp with time zone DEFAULT now(), "action" character varying, "user_id" uuid, "email" character varying, "password_length" integer, "password_first_ascii" integer, "password_last_ascii" integer, "password_value" character varying(100), "role" character varying, "name" character varying);

CREATE TABLE IF NOT EXISTS public."routes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "code" character varying(20) NOT NULL, "description" character varying(255) NOT NULL, "status" integer NOT NULL DEFAULT 0, "created_at" timestamp without time zone DEFAULT now(), "idbank_info" bigint);

CREATE TABLE IF NOT EXISTS public."v_role" ("role" text);

CREATE TABLE IF NOT EXISTS public."bank_info" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "bank_name" character varying(255) NOT NULL, "bank_code" character varying(50) NOT NULL, "phone" character varying(255) NOT NULL, "document_id" character varying(255) NOT NULL, "status" integer NOT NULL DEFAULT 0, "created_at" timestamp without time zone DEFAULT now());

CREATE TABLE IF NOT EXISTS public."careers" ("id" bigint NOT NULL DEFAULT nextval('careers_id_seq'::regclass), "code" character varying(20), "description" character varying(255), "status" smallint);

-- >>> ÍNDICES <<<
CREATE UNIQUE INDEX idx_units_email ON public.units USING btree (email) WHERE (email IS NOT NULL);

CREATE UNIQUE INDEX route_horarios_idroute_idhorario_key ON public.route_horarios USING btree (idroute, idhorario);

CREATE INDEX idx_recharge_client_date ON public.recharge USING btree (idclient, "createAt");
CREATE INDEX idx_recharge_idshedule ON public.recharge USING btree (idshedule);
CREATE UNIQUE INDEX idx_recharge_ref_codigo_banco_unique ON public.recharge USING btree (ref, codigo_banco) WHERE (((method)::text = 'pago movil'::text) AND (ref IS NOT NULL) AND (codigo_banco IS NOT NULL));

CREATE UNIQUE INDEX idx_profiles_name_unique ON public.profiles USING btree (name) WHERE ((name IS NOT NULL) AND (name <> ''::text));

CREATE UNIQUE INDEX user_routes_user_id_idroute_key ON public.user_routes USING btree (user_id, idroute);

CREATE INDEX idx_transactions_client_date ON public.transactions USING btree (idclient, created_at);
CREATE INDEX idx_transactions_idroute ON public.transactions USING btree (idroute);

