-- ============================================================
-- Migración completa: Stops + Refactor company.ticket → stop price
-- Fecha: 2026-08-21
-- Descripción: Script único que incluye:
--   A) Tablas stops / route_stops + RLS + 3 RPCs CRUD
--   B) Refactor de company.ticket → route_stops.price en 4 RPCs
--   C) Deprecación de charge_ticket
-- ============================================================

-- ============================================================
-- PARTE A: Stops + Route Stops (tablas, RLS, RPCs)
-- ============================================================

-- A1. Tabla stops
CREATE TABLE IF NOT EXISTS public."stops" (
    "id"          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        character varying(255) NOT NULL,
    "description" character varying(255) DEFAULT ''::character varying,
    "status"      integer NOT NULL DEFAULT 0,
    "created_at"  timestamp with time zone DEFAULT now()
);

ALTER TABLE public."stops" DROP CONSTRAINT IF EXISTS "stops_pkey" CASCADE;
ALTER TABLE public."stops" ADD CONSTRAINT "stops_pkey" PRIMARY KEY (id);
CREATE INDEX IF NOT EXISTS "idx_stops_name" ON public."stops" ("name");

-- A2. Tabla route_stops
CREATE TABLE IF NOT EXISTS public."route_stops" (
    "id"         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "route_id"   bigint NOT NULL,
    "stop_id"    bigint NOT NULL,
    "price"      numeric(10,2) NOT NULL DEFAULT 0,
    "stop_order" integer NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE public."route_stops" DROP CONSTRAINT IF EXISTS "route_stops_pkey" CASCADE;
ALTER TABLE public."route_stops" ADD CONSTRAINT "route_stops_pkey" PRIMARY KEY (id);

ALTER TABLE public."route_stops" DROP CONSTRAINT IF EXISTS "route_stops_route_id_fkey" CASCADE;
ALTER TABLE public."route_stops"
    ADD CONSTRAINT "route_stops_route_id_fkey"
    FOREIGN KEY ("route_id") REFERENCES public."routes"("id") ON DELETE CASCADE;

ALTER TABLE public."route_stops" DROP CONSTRAINT IF EXISTS "route_stops_stop_id_fkey" CASCADE;
ALTER TABLE public."route_stops"
    ADD CONSTRAINT "route_stops_stop_id_fkey"
    FOREIGN KEY ("stop_id") REFERENCES public."stops"("id") ON DELETE CASCADE;

ALTER TABLE public."route_stops" DROP CONSTRAINT IF EXISTS "route_stops_route_stop_uq" CASCADE;
ALTER TABLE public."route_stops"
    ADD CONSTRAINT "route_stops_route_stop_uq"
    UNIQUE ("route_id", "stop_id");

CREATE INDEX IF NOT EXISTS "idx_route_stops_route_id" ON public."route_stops" ("route_id");
CREATE INDEX IF NOT EXISTS "idx_route_stops_stop_id"  ON public."route_stops" ("stop_id");

-- A3. RLS
ALTER TABLE public."stops" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."route_stops" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stops_select_all"   ON public."stops";
DROP POLICY IF EXISTS "stops_insert_admin" ON public."stops";
DROP POLICY IF EXISTS "stops_update_admin" ON public."stops";
DROP POLICY IF EXISTS "stops_delete_admin" ON public."stops";

CREATE POLICY "stops_select_all"   ON public."stops" FOR SELECT TO authenticated USING (true);
CREATE POLICY "stops_insert_admin" ON public."stops" FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "stops_update_admin" ON public."stops" FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "stops_delete_admin" ON public."stops" FOR DELETE TO authenticated USING (is_admin());

DROP POLICY IF EXISTS "route_stops_select_all"   ON public."route_stops";
DROP POLICY IF EXISTS "route_stops_insert_admin" ON public."route_stops";
DROP POLICY IF EXISTS "route_stops_update_admin" ON public."route_stops";
DROP POLICY IF EXISTS "route_stops_delete_admin" ON public."route_stops";

CREATE POLICY "route_stops_select_all"   ON public."route_stops" FOR SELECT TO authenticated USING (true);
CREATE POLICY "route_stops_insert_admin" ON public."route_stops" FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "route_stops_update_admin" ON public."route_stops" FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "route_stops_delete_admin" ON public."route_stops" FOR DELETE TO authenticated USING (is_admin());

-- A4. RPC: manage_stop
DROP FUNCTION IF EXISTS public.manage_stop(character varying, bigint, character varying, character varying, integer);
CREATE OR REPLACE FUNCTION public.manage_stop(
    p_action      character varying,
    p_id          bigint DEFAULT NULL,
    p_name        character varying DEFAULT NULL,
    p_description character varying DEFAULT NULL,
    p_status      integer DEFAULT NULL
)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_stop JSON;
BEGIN
    IF LOWER(p_action) = 'list' THEN
        SELECT json_agg(row_to_json(s.*)) INTO v_stop FROM (
            SELECT * FROM public.stops ORDER BY id
        ) s;
        RETURN json_build_object('success', true, 'data', COALESCE(v_stop, '[]'::json));
    END IF;

    IF NOT public.is_admin() THEN
        RETURN json_build_object('success', false, 'message', 'Solo administradores pueden realizar esta accion.');
    END IF;

    IF LOWER(p_action) = 'create' THEN
        WITH inserted AS (
            INSERT INTO public.stops (name, description, status)
            VALUES (p_name, COALESCE(p_description, ''), COALESCE(p_status, 0))
            RETURNING *
        )
        SELECT row_to_json(inserted.*) INTO v_stop FROM inserted;
        RETURN json_build_object('success', true, 'data', v_stop, 'message', 'Parada creada con exito.');

    ELSIF LOWER(p_action) = 'update' THEN
        WITH updated AS (
            UPDATE public.stops SET
                name        = COALESCE(p_name, name),
                description = COALESCE(p_description, description),
                status      = COALESCE(p_status, status)
            WHERE id = p_id
            RETURNING *
        )
        SELECT row_to_json(updated.*) INTO v_stop FROM updated;
        RETURN json_build_object('success', true, 'data', v_stop, 'message', 'Parada actualizada con exito.');

    ELSIF LOWER(p_action) = 'delete' THEN
        DELETE FROM public.stops WHERE id = p_id;
        RETURN json_build_object('success', true, 'message', 'Parada eliminada del sistema.');

    ELSE
        RETURN json_build_object('success', false, 'message', 'Accion no reconocida.');
    END IF;

EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Error: ' || SQLERRM);
END;
$function$
;

-- A5. RPC: get_stops_by_route
DROP FUNCTION IF EXISTS public.get_stops_by_route(bigint);
CREATE OR REPLACE FUNCTION public.get_stops_by_route(p_idroute bigint)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_data JSON;
BEGIN
  IF auth.role() <> 'authenticated' THEN
    RETURN json_build_object('success', false, 'data', '[]'::json);
  END IF;
  SELECT json_agg(json_build_object(
    'id', rs.id,
    'route_id', rs.route_id,
    'stop_id', rs.stop_id,
    'price', rs.price,
    'stop_order', rs.stop_order,
    'name', s.name,
    'description', s.description
  ) ORDER BY rs.stop_order) INTO v_data
  FROM public.route_stops rs
  INNER JOIN public.stops s ON s.id = rs.stop_id
  WHERE rs.route_id = p_idroute;
  RETURN json_build_object('success', true, 'data', COALESCE(v_data, '[]'::json));
END;
$function$
;

-- A6. RPC: manage_route_stop
DROP FUNCTION IF EXISTS public.manage_route_stop(character varying, bigint, bigint, bigint, numeric, integer);
CREATE OR REPLACE FUNCTION public.manage_route_stop(
    p_action    character varying,
    p_id        bigint DEFAULT NULL,
    p_route_id  bigint DEFAULT NULL,
    p_stop_id   bigint DEFAULT NULL,
    p_price     numeric DEFAULT NULL,
    p_stop_order integer DEFAULT NULL
)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_data JSON;
BEGIN
  IF LOWER(p_action) = 'list_by_route' THEN
    IF auth.role() <> 'authenticated' THEN
      RETURN json_build_object('success', false, 'message', 'No autorizado.');
    END IF;
    SELECT json_agg(json_build_object(
      'id', rs.id,
      'route_id', rs.route_id,
      'stop_id', rs.stop_id,
      'price', rs.price,
      'stop_order', rs.stop_order,
      'name', s.name,
      'description', s.description
    ) ORDER BY rs.stop_order) INTO v_data
    FROM public.route_stops rs
    INNER JOIN public.stops s ON s.id = rs.stop_id
    WHERE rs.route_id = p_route_id;
    RETURN json_build_object('success', true, 'data', COALESCE(v_data, '[]'::json));
  END IF;

  IF NOT public.is_admin() THEN
    RETURN json_build_object('success', false, 'message', 'Solo administradores pueden realizar esta accion.');
  END IF;

  IF LOWER(p_action) = 'create' THEN
    INSERT INTO public.route_stops (route_id, stop_id, price, stop_order)
    VALUES (p_route_id, p_stop_id, COALESCE(p_price, 0), COALESCE(p_stop_order, 0))
    ON CONFLICT (route_id, stop_id) DO NOTHING
    RETURNING id INTO v_data;
    IF v_data IS NULL THEN
      RETURN json_build_object('success', false, 'message', 'La parada ya esta asignada a esta ruta.');
    END IF;
    RETURN json_build_object('success', true, 'data', json_build_object('id', v_data), 'message', 'Parada asignada a la ruta con exito.');

  ELSIF LOWER(p_action) = 'update' THEN
    WITH updated AS (
      UPDATE public.route_stops SET
        price      = COALESCE(p_price, price),
        stop_order = COALESCE(p_stop_order, stop_order)
      WHERE id = p_id
      RETURNING *
    )
    SELECT row_to_json(updated.*) INTO v_data FROM updated;
    IF v_data IS NULL THEN
      RETURN json_build_object('success', false, 'message', 'Registro no encontrado.');
    END IF;
    RETURN json_build_object('success', true, 'data', v_data, 'message', 'Parada actualizada con exito.');

  ELSIF LOWER(p_action) = 'delete' THEN
    DELETE FROM public.route_stops WHERE id = p_id;
    RETURN json_build_object('success', true, 'message', 'Parada removida de la ruta con exito.');

  ELSIF LOWER(p_action) = 'delete_by_route' THEN
    DELETE FROM public.route_stops WHERE route_id = p_route_id;
    RETURN json_build_object('success', true, 'message', 'Todas las paradas removidas de la ruta.');

  ELSE
    RETURN json_build_object('success', false, 'message', 'Accion no reconocida.');
  END IF;

EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Error: ' || SQLERRM);
END;
$function$
;


-- ============================================================
-- PARTE B: Refactor company.ticket → route_stops.price
-- ============================================================

-- B1. process_recharge_status: precio de parada de la ruta
DROP FUNCTION IF EXISTS public.process_recharge_status(bigint, character varying, character varying);
CREATE OR REPLACE FUNCTION public.process_recharge_status(p_recharge_id bigint, p_action character varying, p_approved_by character varying DEFAULT NULL::character varying)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_idclient INTEGER;
    v_status INTEGER;
    v_amount NUMERIC(10,2);
    v_tasa NUMERIC(10,2);
    v_method VARCHAR(255);
    v_idroute BIGINT;
    v_tickets_to_add NUMERIC(10,2) := 0.00;
    v_new_balance NUMERIC(10,2);
    v_final_status INTEGER;
    v_log_message VARCHAR(255);
    v_ticket_price NUMERIC(10,2);
BEGIN
    IF LOWER(p_action) NOT IN ('approve', 'reject') THEN
        RETURN json_build_object('success', false, 'message', 'Accion invalida. Use ''approve'' o ''reject''.');
    END IF;

    SELECT idclient, status, amount, tasa, method, idroute
    INTO v_idclient, v_status, v_amount, v_tasa, v_method, v_idroute
    FROM public.recharge
    WHERE id = p_recharge_id
    FOR UPDATE;

    IF v_idclient IS NULL THEN
        RETURN json_build_object('success', false, 'message', 'La recarga especificada no existe.');
    END IF;

    IF v_status != 0 THEN
        RETURN json_build_object('success', false, 'message', 'Esta recarga ya fue procesada previamente.');
    END IF;

    -- Precio de la primera parada de la ruta, fallback a company.ticket
    SELECT rs.price INTO v_ticket_price
    FROM public.route_stops rs
    WHERE rs.route_id = v_idroute
    ORDER BY rs.stop_order
    LIMIT 1;

    IF v_ticket_price IS NULL OR v_ticket_price <= 0 THEN
        SELECT ticket INTO v_ticket_price FROM public.company LIMIT 1;
    END IF;

    IF LOWER(p_action) = 'approve' THEN
        v_final_status := 1;
        v_log_message := 'Recarga verificada y tickets acreditados con exito.';
        v_tickets_to_add := TRUNC(v_amount / v_ticket_price, 2);

        UPDATE public.clients
        SET balance = balance + v_tickets_to_add
        WHERE id = v_idclient
        RETURNING balance INTO v_new_balance;

    ELSIF LOWER(p_action) = 'reject' THEN
        v_final_status := 2;
        v_log_message := 'Recarga rechazada por el administrador. No se altero el saldo del cliente.';
        SELECT balance INTO v_new_balance FROM public.clients WHERE id = v_idclient;
    END IF;

    UPDATE public.recharge
    SET status = v_final_status,
        "updateAprobate" = NOW(),
        "createBy" = COALESCE(p_approved_by, "createBy")
    WHERE id = p_recharge_id;

    RETURN json_build_object(
        'success', true,
        'message', v_log_message,
        'recharge_id', p_recharge_id,
        'action_executed', p_action,
        'tickets_credited', v_tickets_to_add,
        'current_client_balance', v_new_balance
    );
EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Error al procesar la operacion: ' || SQLERRM);
END;
$function$
;

-- B2. calculate_tickets: acepta p_idroute, prefiere precio de parada
DROP FUNCTION IF EXISTS public.calculate_tickets(numeric, character varying, numeric);
CREATE OR REPLACE FUNCTION public.calculate_tickets(p_amount numeric, p_method character varying, p_tasa numeric, p_idroute bigint DEFAULT NULL)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_ticket_price NUMERIC(10,2);
    v_amount_in_usd NUMERIC(10,2);
    v_estimated_tickets NUMERIC(10,2);
BEGIN
    -- Precio de la primera parada de la ruta
    IF p_idroute IS NOT NULL THEN
        SELECT rs.price INTO v_ticket_price
        FROM public.route_stops rs
        WHERE rs.route_id = p_idroute
        ORDER BY rs.stop_order
        LIMIT 1;
    END IF;

    -- Fallback a company.ticket
    IF v_ticket_price IS NULL OR v_ticket_price <= 0 THEN
        SELECT ticket INTO v_ticket_price FROM public.company LIMIT 1;
    END IF;

    IF v_ticket_price IS NULL OR v_ticket_price <= 0 THEN
        RAISE EXCEPTION 'Error de configuracion: El precio del ticket no esta configurado.';
    END IF;

    IF LOWER(p_method) = 'efectivo' THEN
        v_amount_in_usd := p_amount;
    ELSE
        IF p_tasa IS NULL OR p_tasa <= 0 THEN
            RAISE EXCEPTION 'Conversion fallida: Se requiere una tasa valida mayor a cero para pagos en Bs.';
        END IF;
        v_amount_in_usd := p_amount / p_tasa;
    END IF;

    v_estimated_tickets := TRUNC(v_amount_in_usd / v_ticket_price, 2);

    RETURN json_build_object(
        'usd_amount', ROUND(v_amount_in_usd, 2),
        'estimated_tickets', v_estimated_tickets
    );
END;
$function$
;

-- B3. process_payment: pasar ruta a calculate_tickets
DROP FUNCTION IF EXISTS public.process_payment(integer, numeric, character varying, character varying, numeric, date, character varying, character varying, character varying, bigint, bigint);
CREATE OR REPLACE FUNCTION public.process_payment(p_idclient integer, p_amount numeric, p_method character varying, p_ref character varying DEFAULT NULL::character varying, p_tasa numeric DEFAULT NULL::numeric, p_date date DEFAULT CURRENT_DATE, p_picture character varying DEFAULT NULL::character varying, p_create_by character varying DEFAULT NULL::character varying, p_codigo_banco character varying DEFAULT NULL::character varying, p_idroute bigint DEFAULT NULL::bigint, p_idshedule bigint DEFAULT NULL::bigint)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_current_balance NUMERIC(10,2);
    v_recharge_id BIGINT;
    v_amount_in_usd NUMERIC(10,2);
    v_estimated_tickets NUMERIC(10,2);
    v_calc JSON;
    v_idroute BIGINT;
BEGIN
    IF auth.role() <> 'authenticated' THEN
        RETURN json_build_object('success', false, 'message', 'No autorizado.');
    END IF;

    IF p_amount <= 0 THEN
        RETURN json_build_object('success', false, 'message', 'El monto de la recarga debe ser mayor a cero.');
    END IF;

    SELECT balance, idroute INTO v_current_balance, v_idroute FROM public.clients WHERE id = p_idclient;
    IF v_current_balance IS NULL THEN
        RETURN json_build_object('success', false, 'message', 'El cliente especificado no existe.');
    END IF;

    IF p_idroute IS NOT NULL THEN
        v_idroute := p_idroute;
    END IF;

    -- Usa precio de parada de la ruta si existe, fallback a company.ticket
    v_calc := public.calculate_tickets(p_amount, p_method, p_tasa, v_idroute);
    v_amount_in_usd := (v_calc->>'usd_amount')::NUMERIC;
    v_estimated_tickets := (v_calc->>'estimated_tickets')::NUMERIC;

    INSERT INTO public.recharge (
        idclient, method, ref, picture, amount, tasa, date, status, "createBy", "createAt", codigo_banco, idroute, tickets, idshedule
    )
    VALUES (
        p_idclient, p_method, NULLIF(p_ref, ''), NULLIF(p_picture, ''),
        v_amount_in_usd, p_tasa, p_date, 0, p_create_by, NOW(),
        NULLIF(p_codigo_banco, ''), v_idroute, v_estimated_tickets, p_idshedule
    )
    RETURNING id INTO v_recharge_id;

    RETURN json_build_object(
        'success', true,
        'message', 'Pago registrado exitosamente. En espera por verificacion administrativa.',
        'recharge_id', v_recharge_id,
        'estimated_tickets', v_estimated_tickets,
        'current_balance', v_current_balance
    );
EXCEPTION
    WHEN SQLSTATE '23505' THEN
        RETURN json_build_object('success', false, 'message', 'Esta combinacion de banco y referencia ya fue procesada. Verifique los datos e intente de nuevo.');
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Error en transaccion: ' || SQLERRM);
END;
$function$
;

-- B4. get_client_by_uid: balance ya esta en tickets, sin dependencia de company.ticket
DROP FUNCTION IF EXISTS public.get_client_by_uid(character varying);
CREATE OR REPLACE FUNCTION public.get_client_by_uid(p_uid character varying)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_client_id BIGINT;
    v_name VARCHAR(255);
    v_balance NUMERIC(10,2);
    v_document_id VARCHAR(255);
    v_photo_url VARCHAR(1000);
BEGIN
    SELECT id, name, balance, "documentID", photo_url
    INTO v_client_id, v_name, v_balance, v_document_id, v_photo_url
    FROM public.clients
    WHERE uid = p_uid
    LIMIT 1;

    IF v_client_id IS NULL THEN
        RETURN json_build_object('success', false, 'message', 'Cliente no encontrado');
    END IF;

    RETURN json_build_object(
        'success', true,
        'data', json_build_object(
            'id', v_client_id,
            'name', v_name,
            'documentID', v_document_id,
            'photo_url', v_photo_url,
            'balance', v_balance,
            'tickets_balance', v_balance
        )
    );
EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Error al consultar el cliente: ' || SQLERRM);
END;
$function$
;

-- B5. charge_ticket: DEPRECATED (sin callers en frontend, usa company.ticket)
-- Se mantiene por compatibilidad. Todos los cobros activos usan charge_tickets_bulk.
COMMENT ON FUNCTION public.charge_ticket(character varying, integer, character varying, integer)
    IS 'DEPRECATED — usar charge_tickets_bulk. Esta funcion resta USD del balance usando company.ticket global.';
