-- ============================================================
-- Migración: stops + route_stops
-- Fecha: 2025-06-25
-- Descripción: Tabla de paradas, relación N:N con routes,
--              y 3 RPCs: manage_stop, get_stops_by_route,
--              manage_route_stop.
-- ============================================================

-- 1. Tabla stops
CREATE TABLE IF NOT EXISTS public."stops" (
    "id"          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        character varying(255) NOT NULL,
    "description" character varying(255) DEFAULT ''::character varying,
    "status"      integer NOT NULL DEFAULT 0,
    "created_at"  timestamp with time zone DEFAULT now()
);

ALTER TABLE public."stops" DROP CONSTRAINT IF EXISTS "stops_pkey" CASCADE;
ALTER TABLE public."stops" ADD CONSTRAINT "stops_pkey" PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS "idx_stops_name" ON public."stops" ("name");

-- 2. Tabla intermedia route_stops
CREATE TABLE IF NOT EXISTS public."route_stops" (
    "id"         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "route_id"   bigint NOT NULL,
    "stop_id"    bigint NOT NULL,
    "price"      numeric(10,2) NOT NULL DEFAULT 0,
    "stop_order" integer NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE public."route_stops" DROP CONSTRAINT IF EXISTS "route_stops_pkey" CASCADE;
ALTER TABLE public."route_stops" ADD CONSTRAINT "route_stops_pkey" PRIMARY KEY (id);

-- FKs
ALTER TABLE public."route_stops" DROP CONSTRAINT IF EXISTS "route_stops_route_id_fkey" CASCADE;
ALTER TABLE public."route_stops"
    ADD CONSTRAINT "route_stops_route_id_fkey"
    FOREIGN KEY ("route_id") REFERENCES public."routes"("id") ON DELETE CASCADE;

ALTER TABLE public."route_stops" DROP CONSTRAINT IF EXISTS "route_stops_stop_id_fkey" CASCADE;
ALTER TABLE public."route_stops"
    ADD CONSTRAINT "route_stops_stop_id_fkey"
    FOREIGN KEY ("stop_id") REFERENCES public."stops"("id") ON DELETE CASCADE;

-- Unique constraint
ALTER TABLE public."route_stops" DROP CONSTRAINT IF EXISTS "route_stops_route_stop_uq" CASCADE;
ALTER TABLE public."route_stops"
    ADD CONSTRAINT "route_stops_route_stop_uq"
    UNIQUE ("route_id", "stop_id");

-- Índices
CREATE INDEX IF NOT EXISTS "idx_route_stops_route_id" ON public."route_stops" ("route_id");
CREATE INDEX IF NOT EXISTS "idx_route_stops_stop_id"  ON public."route_stops" ("stop_id");

-- 3. RLS
ALTER TABLE public."stops" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."route_stops" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stops_select_all"   ON public."stops";
DROP POLICY IF EXISTS "stops_insert_admin" ON public."stops";
DROP POLICY IF EXISTS "stops_update_admin" ON public."stops";
DROP POLICY IF EXISTS "stops_delete_admin" ON public."stops";

CREATE POLICY "stops_select_all"   ON public."stops" FOR SELECT TO authenticated USING (true);
CREATE POLICY "stops_insert_admin" ON public."stops" FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "stops_update_admin" ON public."stops" FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "stops_delete_admin" ON public."stops" FOR DELETE TO authenticated USING (is_admin());

DROP POLICY IF EXISTS "route_stops_select_all"   ON public."route_stops";
DROP POLICY IF EXISTS "route_stops_insert_admin" ON public."route_stops";
DROP POLICY IF EXISTS "route_stops_update_admin" ON public."route_stops";
DROP POLICY IF EXISTS "route_stops_delete_admin" ON public."route_stops";

CREATE POLICY "route_stops_select_all"   ON public."route_stops" FOR SELECT TO authenticated USING (true);
CREATE POLICY "route_stops_insert_admin" ON public."route_stops" FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "route_stops_update_admin" ON public."route_stops" FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "route_stops_delete_admin" ON public."route_stops" FOR DELETE TO authenticated USING (is_admin());

-- 4. RPC: manage_stop
DROP FUNCTION IF EXISTS public.manage_stop(character varying, bigint, character varying, character varying, integer);
CREATE OR REPLACE FUNCTION public.manage_stop(
    p_action      character varying,
    p_id          bigint DEFAULT NULL,
    p_name        character varying DEFAULT NULL,
    p_description character varying DEFAULT NULL,
    p_status      integer DEFAULT NULL
)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_stop JSON;
BEGIN
    IF LOWER(p_action) = 'list' THEN
        SELECT json_agg(row_to_json(s.*)) INTO v_stop FROM (
            SELECT * FROM public.stops ORDER BY id
        ) s;
        RETURN json_build_object('success', true, 'data', COALESCE(v_stop, '[]'::json));
    END IF;

    IF NOT public.is_admin() THEN
        RETURN json_build_object('success', false, 'message', 'Solo administradores pueden realizar esta accion.');
    END IF;

    IF LOWER(p_action) = 'create' THEN
        WITH inserted AS (
            INSERT INTO public.stops (name, description, status)
            VALUES (p_name, COALESCE(p_description, ''), COALESCE(p_status, 0))
            RETURNING *
        )
        SELECT row_to_json(inserted.*) INTO v_stop FROM inserted;
        RETURN json_build_object('success', true, 'data', v_stop, 'message', 'Parada creada con exito.');

    ELSIF LOWER(p_action) = 'update' THEN
        WITH updated AS (
            UPDATE public.stops SET
                name        = COALESCE(p_name, name),
                description = COALESCE(p_description, description),
                status      = COALESCE(p_status, status)
            WHERE id = p_id
            RETURNING *
        )
        SELECT row_to_json(updated.*) INTO v_stop FROM updated;
        RETURN json_build_object('success', true, 'data', v_stop, 'message', 'Parada actualizada con exito.');

    ELSIF LOWER(p_action) = 'delete' THEN
        DELETE FROM public.stops WHERE id = p_id;
        RETURN json_build_object('success', true, 'message', 'Parada eliminada del sistema.');

    ELSE
        RETURN json_build_object('success', false, 'message', 'Accion no reconocida.');
    END IF;

EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Error: ' || SQLERRM);
END;
$function$
;

-- 5. RPC: get_stops_by_route
DROP FUNCTION IF EXISTS public.get_stops_by_route(bigint);
CREATE OR REPLACE FUNCTION public.get_stops_by_route(p_idroute bigint)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_data JSON;
BEGIN
  IF auth.role() <> 'authenticated' THEN
    RETURN json_build_object('success', false, 'data', '[]'::json);
  END IF;
  SELECT json_agg(json_build_object(
    'id', rs.id,
    'route_id', rs.route_id,
    'stop_id', rs.stop_id,
    'price', rs.price,
    'stop_order', rs.stop_order,
    'name', s.name,
    'description', s.description
  ) ORDER BY rs.stop_order) INTO v_data
  FROM public.route_stops rs
  INNER JOIN public.stops s ON s.id = rs.stop_id
  WHERE rs.route_id = p_idroute;
  RETURN json_build_object('success', true, 'data', COALESCE(v_data, '[]'::json));
END;
$function$
;

-- 6. RPC: manage_route_stop
DROP FUNCTION IF EXISTS public.manage_route_stop(character varying, bigint, bigint, bigint, numeric, integer);
CREATE OR REPLACE FUNCTION public.manage_route_stop(
    p_action    character varying,
    p_id        bigint DEFAULT NULL,
    p_route_id  bigint DEFAULT NULL,
    p_stop_id   bigint DEFAULT NULL,
    p_price     numeric DEFAULT NULL,
    p_stop_order integer DEFAULT NULL
)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_data JSON;
BEGIN
  IF LOWER(p_action) = 'list_by_route' THEN
    IF auth.role() <> 'authenticated' THEN
      RETURN json_build_object('success', false, 'message', 'No autorizado.');
    END IF;
    SELECT json_agg(json_build_object(
      'id', rs.id,
      'route_id', rs.route_id,
      'stop_id', rs.stop_id,
      'price', rs.price,
      'stop_order', rs.stop_order,
      'name', s.name,
      'description', s.description
    ) ORDER BY rs.stop_order) INTO v_data
    FROM public.route_stops rs
    INNER JOIN public.stops s ON s.id = rs.stop_id
    WHERE rs.route_id = p_route_id;
    RETURN json_build_object('success', true, 'data', COALESCE(v_data, '[]'::json));
  END IF;

  IF NOT public.is_admin() THEN
    RETURN json_build_object('success', false, 'message', 'Solo administradores pueden realizar esta accion.');
  END IF;

  IF LOWER(p_action) = 'create' THEN
    INSERT INTO public.route_stops (route_id, stop_id, price, stop_order)
    VALUES (p_route_id, p_stop_id, COALESCE(p_price, 0), COALESCE(p_stop_order, 0))
    ON CONFLICT (route_id, stop_id) DO NOTHING
    RETURNING id INTO v_data;
    IF v_data IS NULL THEN
      RETURN json_build_object('success', false, 'message', 'La parada ya esta asignada a esta ruta.');
    END IF;
    RETURN json_build_object('success', true, 'data', json_build_object('id', v_data), 'message', 'Parada asignada a la ruta con exito.');

  ELSIF LOWER(p_action) = 'update' THEN
    WITH updated AS (
      UPDATE public.route_stops SET
        price      = COALESCE(p_price, price),
        stop_order = COALESCE(p_stop_order, stop_order)
      WHERE id = p_id
      RETURNING *
    )
    SELECT row_to_json(updated.*) INTO v_data FROM updated;
    IF v_data IS NULL THEN
      RETURN json_build_object('success', false, 'message', 'Registro no encontrado.');
    END IF;
    RETURN json_build_object('success', true, 'data', v_data, 'message', 'Parada actualizada con exito.');

  ELSIF LOWER(p_action) = 'delete' THEN
    DELETE FROM public.route_stops WHERE id = p_id;
    RETURN json_build_object('success', true, 'message', 'Parada removida de la ruta con exito.');

  ELSIF LOWER(p_action) = 'delete_by_route' THEN
    DELETE FROM public.route_stops WHERE route_id = p_route_id;
    RETURN json_build_object('success', true, 'message', 'Todas las paradas removidas de la ruta.');

  ELSE
    RETURN json_build_object('success', false, 'message', 'Accion no reconocida.');
  END IF;

EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Error: ' || SQLERRM);
END;
$function$
;
